### ISSUE TITLE
Two way bridge?

### ISSUE THREAD

**Issue by sftpocketmine** [eDroiid/ChatToDiscord#1]
I asked NiekertDev if he would be able to add a two way bridge so that not only can the server send the ingame chat to discord but people could go on a discord server and send messages back to the server so that they can easily talk to their friends ingame and such; however, he didn't seem to want to do that, so I was wondering if you'd be able/willing to give it a try? It'd be so awesome if you could :heart: 

Something like this but for PE is what I'm referring to: https://github.com/destruc7i0n/shulker

I'd really appreciate it if you could add this, that's really all that I want lol

**Comment by eDroiid** [comment]
Im sorry, but this request is out of out of my comfort zone, but i heard Thunder33345 and HittmanA are willing to create one but there is only a 40% chance they might.
