### ISSUE TITLE
Update 3.0.0-ALPHA7

### ISSUE THREAD

**Issue by teracube** [eDroiid/ChatToDiscord#2]
Hi,

Is AntiCheat exist in 3.0.0-ALPHA7 version ?

Thanks for this good application

Antoine

**Comment by TheDeibo** [comment]
1. What is anti cheat?
2. What is it related to this project?
3. This project is a plugin, not application.

**Comment by teracube** [comment]
Hi,
sorry for the mistake, i vas tired.
Is ChatToDiscord exist in 3.0.0-ALPHA7 version ?
thanks

**Comment by eDroiid** [comment]
Yes, ChatToDiscord is now 3.0.0-ALPHA7. But it is not updated in Poggit.
