### ISSUE TITLE
Copycat

### ISSUE THREAD

**Issue by NiekertDev** [eDroiid/ChatToDiscord#3]
Copycat.... You just copy me.

**Comment by eDroiid** [comment]
Uhh no i dont..

**Comment by NiekertDev** [comment]
Uh why you make same faupt as me in sendMessage? It now had bad security

**Comment by Thunder33345** [comment]
i think cuz i used to do that before i got proper CURL cert setup :P

**Comment by eDroiid** [comment]
@NiekertDev why do you care?
