### ISSUE TITLE
upgrade Alpha8

### ISSUE THREAD

**Issue by teracube** [eDroiid/ChatToDiscord#4]
Hi,
Please upgrade Alpha8
thanks

**Comment by teracube** [comment]
Or Alpha9 now
thanks

**Comment by eDroiid** [comment]
https://github.com/eDroiid/ChatToDiscord/commit/23c0f69cb9d7e4ce6f5a2a9c73c39b9101a492f1

updated.. check poggit.

**Comment by teracube** [comment]
thank you ;-)
